export const RESUME_DATA = {
  name: "Moaksh Kakkar",
  contact: {
    email: "moakshkakar@gmail.com",
    phone: "+91 9560511269",
    linkedin: "linkedin.com/MoakshKakkar",
    github: "github.com/Moaksh",
  },
  education: [
    {
      institution: "Bennett University",
      degree: "Bachelor Of Technology (Computer Science)",
      date: "August 2022 - August 2026",
      location: "Greater Noida, India",
      details: "CGPA: 9.04",
    },
    {
      institution: "Delhi Public School, Rohini",
      degree: "Science",
      date: "March 2020 - July 2022",
      location: "Delhi, India",
      details: "10th: 82% — 12th: 85%",
    },
  ],
  skills: {
    languages: [
      "Python",
      "C++",
      "HTML",
      "CSS",
      "JavaScript",
      "TypeScript",
      "SQL",
    ],
    technologies: [
      "PyTorch",
      "Tensorflow",
      "FastAPI",
      "Numpy",
      "Pandas",
      "Matplotlib",
      "Flask",
      "NextJS",
      "Linux",
      "Docker",
      "StreamLit",
      "TailwindCSS",
      "Git/Github",
      "MongoDB",
      "GenAI Tools",
    ],
  },
  experience: [
    {
      title: "Deep Learning Intern",
      company: "Thothica",
      date: "April 2024 - Dec 2024",
      location: "Remote",
      responsibilities: [
        "Developed and implemented an evaluation method to assess the performance of Tesseract and Surya OCR engines in processing complex Urdu and Hindi scripts. Optimized Surya OCR, resulting in a 35% improvement in Hindi recognition accuracy.",
        "Leveraged OpenAI API to rapidly develop a compelling proof of concept for a client within 24 hours, seamlessly integrating it into a website and hosting it on an AWS EC2 instance, demonstrating innovative solutions and delivering immediate value.",
        "Automated web scraping for Indian literature using Selenium, boosting efficiency by over 70%.",
        "Conducted in-depth research on Retrieval-Augmented Reasoning, exploring innovative methodologies to enhance information retrieval and reasoning capabilities in AI systems.",
      ],
      technologies: [
        "Python",
        "PyTorch",
        "Tesseract",
        "Selenium",
        "GenAI",
        "LLM",
      ],
    },
    {
      title: "Academic Intern",
      company: "National University Singapore",
      date: "June 2023 - July 2023",
      location: "On-Site",
      responsibilities: [
        "Collaborated with and managed a team of five students from diverse Indian universities to develop a Pose Detector within one month.",
        "Evaluated and compared various computer vision frameworks, including MediaPipe and YOLO V7, and selected YOLO V7 for its superior performance and accuracy.",
        "Leveraged the YOLO V7 object detection algorithm to train a model capable of real-time pose estimation.",
        "Explored the potential of custom keypoint detection using Detectron; however, encountered time constraints that prevented full implementation of this approach.",
      ],
      technologies: [
        "Python",
        "Pytorch",
        "YOLOv7",
        "ResNet",
        "InceptionV3",
        "Detectron",
        "Streamlit",
        "GenAI",
      ],
    },
  ],
  projects: [
    {
      title: "On1y One",
      date: "Jan 2024 - March 2024",
      description: [
        "Developed a custom Generative Adversarial Network (GAN) model using a convolutional neural network (CNN) as the generator and a CNN-based discriminator in PyTorch.",
        "Trained the GAN model on a custom dataset of NFT style images sourced from HuggingFace, enabling the generation of unique and diverse NFT-style images through unsupervised learning. Developed an API using FastAPI for easy access and integration.",
        "Designed and directed the website's front-end to ensure seamless functionality across, facilitating efficient production. Integrated the image generator into the website for enhanced user experience.",
      ],
      technologies: [
        "Python",
        "PyTorch",
        "numpy",
        "Flask",
        "HTML",
        "TailwindCSS",
      ],
      link: "#",
    },
    {
      title: "Lip-sync",
      date: "Sept 2023 - Dec 2023",
      description: [
        "Restructured a deep learning model to transcribe text from videos of individuals speaking, leveraging lip movements for improved accuracy.",
        "Preprocessed video data using dlib and OpenCV to extract essential facial information necessary for the model.",
        "Defined a neural network architecture that combines spatial pooling layers to capture spatial lip movements with LSTM layers to model temporal sequences.",
      ],
      technologies: ["Python", "TensorFlow", "StreamLit"],
      link: "#",
    },
  ],
  research: [
    {
      title: "How could we add emotional nuances to AI-generated music?",
      date: "Feb 2025 - Current",
      status: "In Process",
      type: "Research",
      description: [
        "Developing methodologies for enhancing emotional depth in AI-generated music, focusing on emotion-sensitive algorithms and the integration of cultural and contextual knowledge.",
        "Investigating neural architectures for affective expression in AI music systems, including the incorporation of emotion embeddings and hybrid variational autoencoder (VAE) frameworks.",
        "Explored the use of reinforcement learning (RL) with human feedback to create adaptive loops for emotional calibration in AI music generation.",
      ],
    },
    {
      title: "A Comparative Study of BDM and TM in the Age of AI",
      date: "Jan 2025 - March 2025",
      status: "In review process",
      type: "Journal Article",
      description: [
        "Conducted a comparative analysis of Big Data Marketing (BDM) and Traditional Marketing (TM) in the age of AI, evaluating the strengths and weaknesses of each approach.",
        "Analyzed the operational efficiency, customer-specific targeting, and short-term reactivity of AI-driven Big Data Marketing (BDM), in contrast to the brand equity, emotional storytelling, and ethical considerations of Traditional Marketing (TM).",
        "Researched the application of hybrid models that integrate AI-driven BDM and TM, to leverage the precision and responsiveness of AI with the cultural awareness and credibility-building properties of traditional marketing.",
      ],
    },
    {
      title: "ISLR using Deep Learning: Attention is Everywhere",
      date: "Sept 2024 - Dec 2024",
      status: "Accepted",
      type: "Conference Proceeding",
      description: [
        "Developed an attention-based LSTM model for Indian Sign Language (ISL) recognition, achieving 94% classification accuracy.",
        "Designed a novel approach to capture temporal dependencies in ISL gestures by processing video as a stream of single frames.",
        "Integrated CNNs and LSTMs to leverage spatial feature extraction and temporal dependencies in gesture recognition.",
        "Focused on computational efficiency to enable real-time applicability in resource-constrained environments.",
      ],
    },
    {
      title: "AI in Finance: Navigating Ethical Quandaries",
      date: "Aug 2024 - Sept 2024",
      status: "Accepted",
      type: "Book Chapter",
      description: [
        "Investigated the challenges and opportunities of integrating AI in finance, including algorithmic bias, transparency, and accountability.",
        "Researched the role of Explainable AI (XAI) and Responsible AI in addressing ethical concerns in AI-driven finance.",
        "Synthesized findings on real-world cases and their management to illustrate the impact of ethical issues.",
        "Outlined guidelines for the ethical development of AI in finance, emphasizing fairness, accountability, and transparency.",
        "Recommended best practices for implementing Responsible AI, including stakeholder engagement, ethical AI frameworks, and continuous monitoring.",
      ],
    },
  ],
  achievements: [
    {
      title: "Certificate of Achievement",
      description: "Fork-it Hackathon (2nd Position)",
      organization: "IIIT Delhi",
    },
    {
      title: "Certificate of Achievement",
      description: "Engineering Project Showcase 2023 (3rd Position)",
      organization: "Bennett University",
    },
    {
      title: "Vice-President",
      description: "Artificial Intelligence Society (AI club of BU)",
      organization: "Bennett University",
    },
    {
      title: "AI Expert",
      description: "GDSC BU (Google Developer Student Club)",
      organization: "Bennett University",
    },
    {
      title: "Tech Head",
      description: "ICosmic'22",
      organization: "Bennett University",
    },
  ],
};
